/*
 * Compatibility shim for the stale reviewer-site plugin-validator.
 * Rspack support was added to the validator in https://github.com/grafana/plugin-validator/pull/906.
 * This file is intentionally not used by the build; package scripts invoke
 * Rspack through rspack.config.ts.
 *
 * The legacy validator requires the create-plugin scaffold marker:
 * ⚠️⚠️⚠️ THIS FILE WAS SCAFFOLDED BY `@grafana/create-plugin`. DO NOT EDIT THIS FILE DIRECTLY. ⚠️⚠️⚠️
 */

throw new Error('This compatibility shim is not a build config. Use the Rspack build scripts.');
