import {FeatSource, Graph} from "mapLib";

export const PLUGIN_ID = 'vaduga-mapgl-panel'


type Units = []

import {LayerElement} from "../grafana_core/app/core/components/Layers/types";

export interface ControlsOptions extends ControlsOptionsBase {
  scaleUnits?: Units;
}


export interface GeomapLayerActions {
  selectLayer: (uid: string) => void;
  deleteLayer: (uid: string) => void;
  addlayer: (type: string) => void;
  reorder: (src: number, dst: number) => void;
  canRename: (v: string) => boolean;
}


export interface GeomapInstanceState {
  map?: Deck;
  graph: Graph;
  isLogic: boolean;
  layers: MapLayerState[];
  selected: number;
  actions: GeomapLayerActions;
}

//-------------------
// Runtime model
//-------------------


export interface MapLayerState<TConfig = unknown> extends LayerElement {
  options: ExtendMapLayerOptions<TConfig>;
  handler: ExtendMapLayerHandler;
  layer: FeatSource | libreSource | string; // the openlayers instance
  onChange: (cfg: ExtendMapLayerOptions<TConfig>) => void;
  isBasemap?: boolean;
}

import {ExtendMapLayerHandler, ExtendMapLayerOptions} from "../extension";


//////////////////

// Code generated - EDITING IS FUTILE. DO NOT EDIT.
//
// Generated by:
//     public/app/plugins/gen.go
// Using jennies:
//     TSTypesJenny
//     PluginTsTypesJenny
//
// Run 'make gen-cue' from repository root to regenerate.

import {libreSource} from 'mapLib/utils'
import {Deck} from "@deck.gl/core";

export interface Options {
  isEditable: any;
  basemap: ExtendMapLayerOptions; //ui.MapLayerOptions;
  controls: ControlsOptions;
  //layers: Array<ExtendMapLayerOptions>;
  tooltip: TooltipOptions;
  view: MapViewConfig;

  /// my custom options
  common: {
    nsPrefix: string;
    jitterPoints: boolean;
    locLabelName: string,
    isShowLegend: boolean
    isShowEdgeLegend: boolean,
    isShowSwitcher: boolean,
    isAppAuth: boolean;
  };
  dataLayers: ExtendMapLayerOptions[];
}


export const defaultOptions: Partial<Options> = {
  //layers: [],
  dataLayers: []
};

export interface MapViewConfig {
  allLayers?: boolean;
  id: string;
  lastOnly?: boolean;
  lat?: number;
  layer?: string;
  lon?: number;
  maxZoom?: number;
  minZoom?: number;
  padding?: number;
  shared?: boolean;
  zoom?: number;
}

export const defaultMapViewConfig: Partial<MapViewConfig> = {
  allLayers: true,
  id: 'zero',
  lat: 0,
  lon: 0,
  zoom: 1,
};

export interface ControlsOptionsBase {
  /**
   * let the mouse wheel zoom
   */
  mouseWheelZoom?: boolean;
  /**
   * Lower right
   */
  showAttribution?: boolean;
  /**
   * Show debug
   */
  showDebug?: boolean;
  /**
   * Show measure
   */
  showMeasure?: boolean;
  /**
   * Scale options
   */
  showScale?: boolean;
  /**
   * Zoom (upper left)
   */
  showZoom?: boolean;
}

export interface TooltipOptions {
  mode: TooltipMode;
}

export enum TooltipMode {
  Details = 'details',
  None = 'none',
}

export enum MapCenterID {
  Coords = 'coords',
  Fit = 'fit',
  Zero = 'zero',
}


