import type { CSSProperties } from 'react';
import type { GrafanaTheme2 } from '@grafana/data';

/** Provide host theme values to panel-core's theme-neutral CSS. */
export const getThemeVariables = (theme: GrafanaTheme2): CSSProperties =>
  ({
    '--theme-background-primary': theme.colors.background.primary,
    '--theme-background-secondary': theme.colors.background.secondary,
    '--theme-background-contrast': theme.colors.getContrastText(theme.colors.background.primary),
    '--theme-text-primary': theme.colors.text.primary,
    '--theme-border-weak': theme.colors.border.weak,
    '--theme-accent': theme.colors.primary.main,
    '--theme-accent-border': theme.colors.primary.border,
    '--theme-accent-contrast': theme.colors.primary.contrastText,
    '--theme-accent-hover': theme.colors.primary.shade,
    '--theme-action-hover': theme.colors.action.hover,
    '--theme-radius-default': theme.shape.radius.default,
    '--theme-font-size-body': theme.typography.body.fontSize,
    '--theme-font-size-small': theme.typography.bodySmall.fontSize,
    '--theme-font-size-h4': theme.typography.h4.fontSize,
    '--theme-font-size-h5': theme.typography.h5.fontSize,
    '--theme-z-index-dropdown': theme.zIndex.dropdown,
    '--theme-z-index-portal': theme.zIndex.portal,
    '--theme-spacing-0-125': theme.spacing(0.125),
    '--theme-spacing-0-25': theme.spacing(0.25),
    '--theme-spacing-0-375': theme.spacing(0.375),
    '--theme-spacing-0-5': theme.spacing(0.5),
    '--theme-spacing-0-625': theme.spacing(0.625),
    '--theme-spacing-0-75': theme.spacing(0.75),
    '--theme-spacing-1': theme.spacing(1),
    '--theme-spacing-1-5': theme.spacing(1.5),
    '--theme-spacing-1-7': theme.spacing(1.7),
    '--theme-spacing-1-75': theme.spacing(1.75),
    '--theme-spacing-2': theme.spacing(2),
    '--theme-spacing-2-5': theme.spacing(2.5),
    '--theme-spacing-3': theme.spacing(3),
    '--theme-spacing-3-375': theme.spacing(3.375),
    '--theme-spacing-4': theme.spacing(4),
    '--theme-spacing-5': theme.spacing(5),
    '--theme-spacing-7': theme.spacing(7),
    '--button-size': theme.spacing(3.5),
    '--button-corner-radius': theme.shape.radius.default,
    '--button-background': theme.colors.background.primary,
    '--button-stroke': theme.colors.background.secondary,
    '--button-inner-stroke': '1px solid ' + theme.colors.border.weak,
    '--button-shadow': theme.shadows.z2,
    '--button-icon-idle': theme.colors.text.secondary,
    '--button-icon-hover': theme.colors.text.primary,
    '--button-text': theme.colors.text.primary,
    '--menu-background': theme.colors.background.primary,
    '--menu-text': theme.colors.text.primary,
    '--menu-border': '1px solid ' + theme.colors.border.weak,
    '--menu-shadow': theme.shadows.z2,
    '--menu-item-hover': theme.colors.background.secondary,
    '--tooltip-z-index': theme.zIndex.portal,
  }) as CSSProperties;
